name: smarthire
services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - smarthire-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - smarthire-network  # Add this
  
  backend:
    build: ./backend
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - storage-data:/app/uploads
    networks:
      - smarthire-network  # Add this
    extra_hosts:  # Add this section
      - "host.docker.internal:host-gateway"
    
  frontend:
    build: ./frontend
    env_file: .env
    ports:
      - "4173:4173"
    depends_on:
      - backend
    networks:
      - smarthire-network
  
  minio:
    image: minio/minio
    env_file: .env
    entrypoint:
      - minio
      - server
      - /data
      - --console-address
      - ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - smarthire-network 

  rxresume:
    image: ghcr.io/amruthpillai/reactive-resume:v4.1.8
    env_file: .env
    depends_on:
      - db
      - minio
    ports:
      - "5174:5173"
      - "3000:3000"
      - "6173:6173"
    networks:
      - smarthire-network  # Add this
    extra_hosts:  # Add this section
      - "host.docker.internal:host-gateway"

volumes:
  smarthire-data:
  storage-data:
  minio-data:

networks:
  smarthire-network:
    driver: bridge